/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiGdriveRouteImport } from './routes/api/gdrive'
import { Route as ApiWinesDbRouteImport } from './routes/api/wines-db'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGdriveRoute = ApiGdriveRouteImport.update({
  id: '/api/gdrive',
  path: '/api/gdrive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWinesDbRoute = ApiWinesDbRouteImport.update({
  id: '/api/wines-db',
  path: '/api/wines-db',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/gdrive': typeof ApiGdriveRoute
  '/api/wines-db': typeof ApiWinesDbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/gdrive': typeof ApiGdriveRoute
  '/api/wines-db': typeof ApiWinesDbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/gdrive': typeof ApiGdriveRoute
  '/api/wines-db': typeof ApiWinesDbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth' | '/api/gdrive' | '/api/wines-db'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth' | '/api/gdrive' | '/api/wines-db'
  id: '__root__' | '/' | '/api/auth' | '/api/gdrive' | '/api/wines-db'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiGdriveRoute: typeof ApiGdriveRoute
  ApiWinesDbRoute: typeof ApiWinesDbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gdrive': {
      id: '/api/gdrive'
      path: '/api/gdrive'
      fullPath: '/api/gdrive'
      preLoaderRoute: typeof ApiGdriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wines-db': {
      id: '/api/wines-db'
      path: '/api/wines-db'
      fullPath: '/api/wines-db'
      preLoaderRoute: typeof ApiWinesDbRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiGdriveRoute: ApiGdriveRoute,
  ApiWinesDbRoute: ApiWinesDbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
